# my_timer_core_hw.tcl - Intel Platform Designer Component Definition
# Generated by fpga_lib VHDL Generator
#
# Provides component integration for Intel Quartus Platform Designer (Qsys)
# with Avalon-MM slave interface for register access.
#
# Usage: Place this file in the same directory as your VHDL files and
#        add the directory to Platform Designer's IP search path.

# -----------------------------------------------------------------------------
# Package Definition
# -----------------------------------------------------------------------------
package require qsys

# -----------------------------------------------------------------------------
# Validation Callback
# -----------------------------------------------------------------------------
proc validate {} {
    # Add parameter validation here if needed
}

# -----------------------------------------------------------------------------
# Elaboration Callback
# -----------------------------------------------------------------------------
proc elaborate {} {
    # -----------------------------------------------------------------------------
    # Clock Interface
    # -----------------------------------------------------------------------------
    add_interface clk clock end
    set_interface_property clk clockRate 0
    set_interface_property clk ENABLED true
    set_interface_property clk EXPORT_OF ""
    set_interface_property clk PORT_NAME_MAP ""
    set_interface_property clk CMSIS_SVD_VARIABLES ""
    set_interface_property clk SVD_ADDRESS_GROUP ""

    add_interface_port clk clk clk Input 1

    # -----------------------------------------------------------------------------
    # Reset Interface
    # -----------------------------------------------------------------------------
    add_interface reset reset end
    set_interface_property reset associatedClock clk
    set_interface_property reset synchronousEdges DEASSERT
    set_interface_property reset ENABLED true
    set_interface_property reset EXPORT_OF ""
    set_interface_property reset PORT_NAME_MAP ""
    set_interface_property reset CMSIS_SVD_VARIABLES ""
    set_interface_property reset SVD_ADDRESS_GROUP ""

    add_interface_port reset rst reset Input 1

    # -----------------------------------------------------------------------------
    # Slave Interface
    # -----------------------------------------------------------------------------
    add_interface s0 axi4lite end
    set_interface_property s0 associatedClock clk
    set_interface_property s0 associatedReset reset
    set_interface_property s0 readAcceptanceCapability 1
    set_interface_property s0 writeAcceptanceCapability 1
    set_interface_property s0 combinedAcceptanceCapability 1
    set_interface_property s0 readDataReorderingDepth 1
    set_interface_property s0 bridgesToMaster ""
    set_interface_property s0 ENABLED true
    set_interface_property s0 EXPORT_OF ""
    set_interface_property s0 PORT_NAME_MAP ""
    set_interface_property s0 CMSIS_SVD_VARIABLES ""
    set_interface_property s0 SVD_ADDRESS_GROUP ""

    add_interface_port s0 s0_awaddr awaddr Input 8
    add_interface_port s0 s0_awprot awprot Input 3
    add_interface_port s0 s0_awvalid awvalid Input 1
    add_interface_port s0 s0_awready awready Output 1
    add_interface_port s0 s0_wdata wdata Input 32
    add_interface_port s0 s0_wstrb wstrb Input 4
    add_interface_port s0 s0_wvalid wvalid Input 1
    add_interface_port s0 s0_wready wready Output 1
    add_interface_port s0 s0_bresp bresp Output 2
    add_interface_port s0 s0_bvalid bvalid Output 1
    add_interface_port s0 s0_bready bready Input 1
    add_interface_port s0 s0_araddr araddr Input 8
    add_interface_port s0 s0_arprot arprot Input 3
    add_interface_port s0 s0_arvalid arvalid Input 1
    add_interface_port s0 s0_arready arready Output 1
    add_interface_port s0 s0_rdata rdata Output 32
    add_interface_port s0 s0_rresp rresp Output 2
    add_interface_port s0 s0_rvalid rvalid Output 1
    add_interface_port s0 s0_rready rready Input 1

    # -----------------------------------------------------------------------------
    # Conduit Interface (User Ports)
    # -----------------------------------------------------------------------------
    add_interface conduit conduit end
    set_interface_property conduit associatedClock clk
    set_interface_property conduit associatedReset reset
    set_interface_property conduit ENABLED true
    set_interface_property conduit EXPORT_OF ""
    set_interface_property conduit PORT_NAME_MAP ""
    set_interface_property conduit CMSIS_SVD_VARIABLES ""
    set_interface_property conduit SVD_ADDRESS_GROUP ""

    add_interface_port conduit o_global_irq o_global_irq Output 1
}

# -----------------------------------------------------------------------------
# Module Properties
# -----------------------------------------------------------------------------
set_module_property DESCRIPTION "A 4-channel, 32-bit configurable timer IP with a separate register clock domain and local RAM."
set_module_property NAME my_timer_core
set_module_property VERSION 1.2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "my-company.com"
set_module_property DISPLAY_NAME "My Timer Core"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property VALIDATION_CALLBACK validate
set_module_property ELABORATION_CALLBACK elaborate

# -----------------------------------------------------------------------------
# File Sets
# -----------------------------------------------------------------------------
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL my_timer_core
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file my_timer_core_pkg.vhd VHDL PATH ../rtl/my_timer_core_pkg.vhd
add_fileset_file my_timer_core_regs.vhd VHDL PATH ../rtl/my_timer_core_regs.vhd
add_fileset_file my_timer_core_core.vhd VHDL PATH ../rtl/my_timer_core_core.vhd
add_fileset_file my_timer_core_axil.vhd VHDL PATH ../rtl/my_timer_core_axil.vhd
add_fileset_file my_timer_core.vhd VHDL PATH ../rtl/my_timer_core.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL my_timer_core
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file my_timer_core_pkg.vhd VHDL PATH ../rtl/my_timer_core_pkg.vhd
add_fileset_file my_timer_core_regs.vhd VHDL PATH ../rtl/my_timer_core_regs.vhd
add_fileset_file my_timer_core_core.vhd VHDL PATH ../rtl/my_timer_core_core.vhd
add_fileset_file my_timer_core_axil.vhd VHDL PATH ../rtl/my_timer_core_axil.vhd
add_fileset_file my_timer_core.vhd VHDL PATH ../rtl/my_timer_core.vhd TOP_LEVEL_FILE

# -----------------------------------------------------------------------------
# Parameters
# -----------------------------------------------------------------------------
add_parameter NUM_CHANNELS INTEGER 4
set_parameter_property NUM_CHANNELS DEFAULT_VALUE 4
set_parameter_property NUM_CHANNELS DISPLAY_NAME "Num Channels"
set_parameter_property NUM_CHANNELS TYPE INTEGER
set_parameter_property NUM_CHANNELS UNITS None
set_parameter_property NUM_CHANNELS HDL_PARAMETER true
set_parameter_property NUM_CHANNELS AFFECTS_GENERATION false
set_parameter_property NUM_CHANNELS AFFECTS_ELABORATION true

add_parameter AXI_ADDR_WIDTH INTEGER 32
set_parameter_property AXI_ADDR_WIDTH DEFAULT_VALUE 32
set_parameter_property AXI_ADDR_WIDTH DISPLAY_NAME "Axi Addr Width"
set_parameter_property AXI_ADDR_WIDTH TYPE INTEGER
set_parameter_property AXI_ADDR_WIDTH UNITS None
set_parameter_property AXI_ADDR_WIDTH HDL_PARAMETER true
set_parameter_property AXI_ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property AXI_ADDR_WIDTH AFFECTS_ELABORATION true

add_parameter EVENT_FIFO_DEPTH INTEGER 16
set_parameter_property EVENT_FIFO_DEPTH DEFAULT_VALUE 16
set_parameter_property EVENT_FIFO_DEPTH DISPLAY_NAME "Event Fifo Depth"
set_parameter_property EVENT_FIFO_DEPTH TYPE INTEGER
set_parameter_property EVENT_FIFO_DEPTH UNITS None
set_parameter_property EVENT_FIFO_DEPTH HDL_PARAMETER true
set_parameter_property EVENT_FIFO_DEPTH AFFECTS_GENERATION false
set_parameter_property EVENT_FIFO_DEPTH AFFECTS_ELABORATION true

add_parameter TIMESTAMP_WIDTH INTEGER 48
set_parameter_property TIMESTAMP_WIDTH DEFAULT_VALUE 48
set_parameter_property TIMESTAMP_WIDTH DISPLAY_NAME "Timestamp Width"
set_parameter_property TIMESTAMP_WIDTH TYPE INTEGER
set_parameter_property TIMESTAMP_WIDTH UNITS None
set_parameter_property TIMESTAMP_WIDTH HDL_PARAMETER true
set_parameter_property TIMESTAMP_WIDTH AFFECTS_GENERATION false
set_parameter_property TIMESTAMP_WIDTH AFFECTS_ELABORATION true

