/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema version (e.g., 'my-ip-schema/v2.3')
 */
export type ApiVersion = string;
/**
 * Vendor identifier (e.g., 'my-company.com')
 */
export type Vendor = string;
/**
 * Library name (e.g., 'processing')
 */
export type Library = string;
/**
 * IP core name (e.g., 'my_timer_core')
 */
export type Name = string;
/**
 * Version string (e.g., '1.2.0')
 */
export type Version = string;
/**
 * IP core description
 */
export type Description = string;
/**
 * Logical port name
 */
export type Name1 = string;
/**
 * Physical port name in HDL
 */
export type PhysicalPort = string;
/**
 * Port direction (typically 'in')
 */
export type PortDirection = "in" | "out" | "inout";
/**
 * Port width in bits
 */
export type Width = number;
/**
 * Port description
 */
export type Description1 = string;
/**
 * Clock frequency (e.g., '100MHz')
 */
export type Frequency = string | null;
/**
 * Clock definitions
 */
export type Clocks = Clock[];
/**
 * Logical port name
 */
export type Name2 = string;
/**
 * Physical port name in HDL
 */
export type PhysicalPort1 = string;
/**
 * Port direction (typically 'in')
 */
export type PortDirection1 = "in" | "out" | "inout";
/**
 * Port width in bits
 */
export type Width1 = number;
/**
 * Port description
 */
export type Description2 = string;
/**
 * Reset polarity (activeHigh or activeLow)
 */
export type Polarity = "activeHigh" | "activeLow";
/**
 * Reset definitions
 */
export type Resets = Reset[];
/**
 * Logical port name
 */
export type Name3 = string;
/**
 * Physical port name in HDL
 */
export type PhysicalPort2 = string;
/**
 * Port direction
 */
export type PortDirection2 = "in" | "out" | "inout";
/**
 * Port width in bits
 */
export type Width2 = number;
/**
 * Port description
 */
export type Description3 = string;
/**
 * Data/control ports
 */
export type Ports = Port[];
/**
 * Logical interface name
 */
export type Name4 = string;
/**
 * Bus type from library (e.g., 'AXI4L', 'AXIS')
 */
export type Type = string;
/**
 * Interface mode: 'master' or 'slave'
 */
export type BusInterfaceMode = "master" | "slave" | "source" | "sink";
/**
 * Prefix for physical port names (e.g., 's_axi_')
 */
export type PhysicalPrefix = string;
/**
 * Logical clock name this interface uses
 */
export type AssociatedClock = string | null;
/**
 * Logical reset name this interface uses
 */
export type AssociatedReset = string | null;
/**
 * Memory map name for register access
 */
export type MemoryMapRef = string | null;
/**
 * List of optional ports to include
 */
export type UseOptionalPorts = string[];
/**
 * Number of instances
 */
export type Count = number;
/**
 * Starting index
 */
export type IndexStart = number;
/**
 * Naming pattern with {index} placeholder (e.g., 'M_AXIS_CH{index}_EVENTS')
 */
export type NamingPattern = string;
/**
 * Physical prefix pattern with {index} placeholder
 */
export type PhysicalPrefixPattern = string;
/**
 * Interface description
 */
export type Description4 = string;
/**
 * Bus interface definitions
 */
export type BusInterfaces = BusInterface[];
/**
 * Memory map name
 */
export type Name5 = string;
/**
 * Memory map description
 */
export type Description5 = string;
/**
 * Block name
 */
export type Name6 = string;
/**
 * Block starting address
 */
export type BaseAddress = number;
/**
 * Block size (bytes or '4K', '1M', etc.)
 */
export type Range = number | string;
/**
 * Block usage type
 */
export type BlockUsage = "register" | "memory" | "reserved";
/**
 * Default access
 */
export type AccessType =
  | "read-only"
  | "write-only"
  | "read-write"
  | "write-1-to-clear"
  | "read-write-1-to-clear"
  | "read-only"
  | "write-only"
  | "read-write"
  | "write-1-to-clear";
/**
 * Block description
 */
export type Description6 = string;
/**
 * Register name
 */
export type Name7 = string;
/**
 * Offset from address block base
 */
export type AddressOffset = number;
/**
 * Register width in bits
 */
export type Size = number;
/**
 * Default access type
 */
export type AccessType1 =
  | "read-only"
  | "write-only"
  | "read-write"
  | "write-1-to-clear"
  | "read-write-1-to-clear"
  | "read-only"
  | "write-only"
  | "read-write"
  | "write-1-to-clear";
/**
 * Reset value for entire register
 */
export type ResetValue = number | null;
/**
 * Register description
 */
export type Description7 = string;
/**
 * Bit field name
 */
export type Name8 = string;
/**
 * Starting bit position (LSB = 0)
 */
export type BitOffset = number;
/**
 * Number of bits
 */
export type BitWidth = number;
/**
 * Access type
 */
export type AccessType2 =
  | "read-only"
  | "write-only"
  | "read-write"
  | "write-1-to-clear"
  | "read-write-1-to-clear"
  | "read-only"
  | "write-only"
  | "read-write"
  | "write-1-to-clear";
/**
 * Reset/default value
 */
export type ResetValue1 = number | null;
/**
 * Field description
 */
export type Description8 = string;
/**
 * Enumeration mapping {value: name}
 */
export type EnumeratedValues = {
  [k: string]: string;
} | null;
/**
 * Bit fields
 */
export type Fields = BitField[];
/**
 * Registers in block
 */
export type Registers = Register[];
/**
 * Base name for array
 */
export type Name9 = string;
/**
 * Starting address
 */
export type BaseAddress1 = number;
/**
 * Number of instances
 */
export type Count1 = number;
/**
 * Address increment between instances
 */
export type Stride = number;
/**
 * Array description
 */
export type Description9 = string;
/**
 * Register arrays
 */
export type RegisterArrays = RegisterArray[];
/**
 * Address blocks
 */
export type AddressBlocks = AddressBlock[];
/**
 * Memory maps
 */
export type MemoryMaps = MemoryMap[];
/**
 * File set name
 */
export type Name10 = string;
/**
 * File set description
 */
export type Description10 = string;
/**
 * Relative or absolute file path
 */
export type Path = string;
/**
 * File type
 */
export type FileType =
  | "vhdl"
  | "verilog"
  | "systemverilog"
  | "xdc"
  | "sdc"
  | "ucf"
  | "cHeader"
  | "cSource"
  | "cppHeader"
  | "cppSource"
  | "pdf"
  | "markdown"
  | "text"
  | "tcl"
  | "yaml"
  | "json"
  | "unknown";
/**
 * File description
 */
export type Description11 = string;
/**
 * Whether file is an include file
 */
export type IsIncludeFile = boolean;
/**
 * Logical name (e.g., library name for VHDL)
 */
export type LogicalName = string;
/**
 * Files in this set
 */
export type Files = File[];
/**
 * File sets
 */
export type FileSets = FileSet[];
/**
 * Parameter name
 */
export type Name11 = string;
/**
 * Data type
 */
export type ParameterType = "integer" | "natural" | "positive" | "real" | "boolean" | "string";
/**
 * Parameter description
 */
export type Description12 = string;
/**
 * Generics/parameters
 */
export type Parameters = Parameter[];
/**
 * Path to bus definitions library
 */
export type UseBusLibrary = string | null;

/**
 * Complete IP core definition - the single source of truth.
 *
 * This is the canonical data model that all parsers produce and
 * all generators consume. It includes:
 * - Metadata (VLNV, description)
 * - Interface definitions (clocks, resets, ports, buses)
 * - Memory maps (registers, bit fields)
 * - Files (HDL sources, constraints, documentation)
 * - Parameters/generics
 */
export interface IpCore {
  api_version: ApiVersion;
  vlnv: VLNV;
  description?: Description;
  clocks?: Clocks;
  resets?: Resets;
  ports?: Ports;
  bus_interfaces?: BusInterfaces;
  memory_maps?: MemoryMaps;
  file_sets?: FileSets;
  parameters?: Parameters;
  use_bus_library?: UseBusLibrary;
}
/**
 * Unique identifier
 */
export interface VLNV {
  vendor: Vendor;
  library: Library;
  name: Name;
  version: Version;
  [k: string]: unknown;
}
/**
 * Clock definition for an IP core.
 *
 * Defines both logical (internal) and physical (port) names for clock signals.
 * Inherits from Port, typically with width=1.
 */
export interface Clock {
  name: Name1;
  physical_port: PhysicalPort;
  direction?: PortDirection;
  width?: Width;
  description?: Description1;
  frequency?: Frequency;
}
/**
 * Reset definition for an IP core.
 *
 * Defines both logical (internal) and physical (port) names for reset signals,
 * including polarity information.
 * Inherits from Port, typically with width=1.
 */
export interface Reset {
  name: Name2;
  physical_port: PhysicalPort1;
  direction?: PortDirection1;
  width?: Width1;
  description?: Description2;
  polarity?: Polarity;
}
/**
 * Generic port definition for IP cores.
 *
 * Used for data and control ports that are not part of clock, reset, or bus interfaces.
 */
export interface Port {
  name: Name3;
  physical_port: PhysicalPort2;
  direction: PortDirection2;
  width?: Width2;
  description?: Description3;
}
/**
 * Bus interface definition for an IP core.
 *
 * Represents a standardized bus connection (AXI, Avalon, etc.) with
 * optional width overrides, clock/reset associations, and array support.
 */
export interface BusInterface {
  name: Name4;
  type: Type;
  mode: BusInterfaceMode;
  physical_prefix: PhysicalPrefix;
  associated_clock?: AssociatedClock;
  associated_reset?: AssociatedReset;
  memory_map_ref?: MemoryMapRef;
  use_optional_ports?: UseOptionalPorts;
  port_width_overrides?: PortWidthOverrides;
  /**
   * Array configuration for multiple instances
   */
  array?: ArrayConfig | null;
  description?: Description4;
}
/**
 * Port width overrides {port_name: width}
 */
export interface PortWidthOverrides {
  [k: string]: number;
}
/**
 * Configuration for array of bus interfaces.
 *
 * Enables creation of multiple interface instances (e.g., 4 AXI Stream channels).
 */
export interface ArrayConfig {
  count: Count;
  index_start?: IndexStart;
  naming_pattern: NamingPattern;
  physical_prefix_pattern: PhysicalPrefixPattern;
}
/**
 * Complete memory map for an IP core.
 *
 * Organizes registers into address blocks with validation.
 */
export interface MemoryMap {
  name: Name5;
  description?: Description5;
  address_blocks?: AddressBlocks;
}
/**
 * Contiguous address block within a memory map.
 *
 * Can contain registers, memory, or reserved space.
 */
export interface AddressBlock {
  name: Name6;
  base_address: BaseAddress;
  range: Range;
  usage?: BlockUsage;
  access?: AccessType;
  description?: Description6;
  registers?: Registers;
  register_arrays?: RegisterArrays;
}
/**
 * Register definition within a memory map.
 *
 * Represents a memory-mapped register with bit fields.
 */
export interface Register {
  name: Name7;
  address_offset: AddressOffset;
  size?: Size;
  access?: AccessType1;
  reset_value?: ResetValue;
  description?: Description7;
  fields?: Fields;
}
/**
 * Bit field within a register.
 *
 * Represents a named range of bits with specific access semantics.
 */
export interface BitField {
  name: Name8;
  bit_offset: BitOffset;
  bit_width: BitWidth;
  access?: AccessType2;
  reset_value?: ResetValue1;
  description?: Description8;
  enumerated_values?: EnumeratedValues;
}
/**
 * Array of registers with automatic address calculation.
 *
 * Used for repeated register structures (e.g., per-channel registers).
 */
export interface RegisterArray {
  name: Name9;
  base_address: BaseAddress1;
  count: Count1;
  stride: Stride;
  template: Register1;
  description?: Description9;
}
/**
 * Register definition within a memory map.
 *
 * Represents a memory-mapped register with bit fields.
 */
export interface Register1 {
  name: Name7;
  address_offset: AddressOffset;
  size?: Size;
  access?: AccessType1;
  reset_value?: ResetValue;
  description?: Description7;
  fields?: Fields;
}
/**
 * Named collection of files for an IP core.
 *
 * Groups related files together (e.g., RTL sources, C API, documentation).
 */
export interface FileSet {
  name: Name10;
  description?: Description10;
  files?: Files;
}
/**
 * File reference within a file set.
 *
 * Represents a file that is part of the IP core (source, constraint, doc, etc.).
 */
export interface File {
  path: Path;
  type: FileType;
  description?: Description11;
  is_include_file?: IsIncludeFile;
  logical_name?: LogicalName;
}
/**
 * Generic parameter/generic definition for IP cores.
 *
 * Used for VHDL generics, Verilog parameters, or component configuration.
 */
export interface Parameter {
  name: Name11;
  value: Value;
  data_type?: ParameterType;
  description?: Description12;
}
/**
 * Default value
 */
export interface Value {
  [k: string]: unknown;
}
