/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Memory map name
 */
export type Name = string;
/**
 * Memory map description
 */
export type Description = string;
/**
 * Block name
 */
export type Name1 = string;
/**
 * Block starting address
 */
export type BaseAddress = number;
/**
 * Block size (bytes or '4K', '1M', etc.)
 */
export type Range = number | string;
/**
 * Block usage type
 */
export type BlockUsage = "register" | "memory" | "reserved";
/**
 * Default access
 */
export type AccessType =
  | "read-only"
  | "write-only"
  | "read-write"
  | "write-1-to-clear"
  | "read-write-1-to-clear"
  | "read-only"
  | "write-only"
  | "read-write"
  | "write-1-to-clear";
/**
 * Block description
 */
export type Description1 = string;
/**
 * Register name
 */
export type Name2 = string;
/**
 * Offset from address block base
 */
export type AddressOffset = number;
/**
 * Register width in bits
 */
export type Size = number;
/**
 * Default access type
 */
export type AccessType1 =
  | "read-only"
  | "write-only"
  | "read-write"
  | "write-1-to-clear"
  | "read-write-1-to-clear"
  | "read-only"
  | "write-only"
  | "read-write"
  | "write-1-to-clear";
/**
 * Reset value for entire register
 */
export type ResetValue = number | null;
/**
 * Register description
 */
export type Description2 = string;
/**
 * Bit field name
 */
export type Name3 = string;
/**
 * Starting bit position (LSB = 0)
 */
export type BitOffset = number;
/**
 * Number of bits
 */
export type BitWidth = number;
/**
 * Access type
 */
export type AccessType2 =
  | "read-only"
  | "write-only"
  | "read-write"
  | "write-1-to-clear"
  | "read-write-1-to-clear"
  | "read-only"
  | "write-only"
  | "read-write"
  | "write-1-to-clear";
/**
 * Reset/default value
 */
export type ResetValue1 = number | null;
/**
 * Field description
 */
export type Description3 = string;
/**
 * Enumeration mapping {value: name}
 */
export type EnumeratedValues = {
  [k: string]: string;
} | null;
/**
 * Bit fields
 */
export type Fields = BitField[];
/**
 * Registers in block
 */
export type Registers = Register[];
/**
 * Base name for array
 */
export type Name4 = string;
/**
 * Starting address
 */
export type BaseAddress1 = number;
/**
 * Number of instances
 */
export type Count = number;
/**
 * Address increment between instances
 */
export type Stride = number;
/**
 * Array description
 */
export type Description4 = string;
/**
 * Register arrays
 */
export type RegisterArrays = RegisterArray[];
/**
 * Address blocks
 */
export type AddressBlocks = AddressBlock[];

/**
 * Complete memory map for an IP core.
 *
 * Organizes registers into address blocks with validation.
 */
export interface MemoryMap {
  name: Name;
  description?: Description;
  address_blocks?: AddressBlocks;
}
/**
 * Contiguous address block within a memory map.
 *
 * Can contain registers, memory, or reserved space.
 */
export interface AddressBlock {
  name: Name1;
  base_address: BaseAddress;
  range: Range;
  usage?: BlockUsage;
  access?: AccessType;
  description?: Description1;
  registers?: Registers;
  register_arrays?: RegisterArrays;
}
/**
 * Register definition within a memory map.
 *
 * Represents a memory-mapped register with bit fields.
 */
export interface Register {
  name: Name2;
  address_offset: AddressOffset;
  size?: Size;
  access?: AccessType1;
  reset_value?: ResetValue;
  description?: Description2;
  fields?: Fields;
}
/**
 * Bit field within a register.
 *
 * Represents a named range of bits with specific access semantics.
 */
export interface BitField {
  name: Name3;
  bit_offset: BitOffset;
  bit_width: BitWidth;
  access?: AccessType2;
  reset_value?: ResetValue1;
  description?: Description3;
  enumerated_values?: EnumeratedValues;
}
/**
 * Array of registers with automatic address calculation.
 *
 * Used for repeated register structures (e.g., per-channel registers).
 */
export interface RegisterArray {
  name: Name4;
  base_address: BaseAddress1;
  count: Count;
  stride: Stride;
  template: Register1;
  description?: Description4;
}
/**
 * Register definition within a memory map.
 *
 * Represents a memory-mapped register with bit fields.
 */
export interface Register1 {
  name: Name2;
  address_offset: AddressOffset;
  size?: Size;
  access?: AccessType1;
  reset_value?: ResetValue;
  description?: Description2;
  fields?: Fields;
}
